version: '3.8'

networks:
  my-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local

services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    container_name: my-mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-lsj123456}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-my_database}"
      MYSQL_USER: "${MYSQL_USER:-root}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-lsj123456}"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-p${MYSQL_ROOT_PASSWORD}"
      retries: 3
      timeout: 5s